### ISSUE TITLE
Cant add bot to my server

### ISSUE THREAD

**Issue by DelusionalMC02** [EmoteBot/EmoteManager#20]
every time i go to add the bot to my server it says that only the applications owner may do this, or something along those limes

**Comment by j3tus** [comment]
Join their discord server to find out why: https://discord.gg/G7rVX8b

**Comment by kconradi87** [comment]
@DelusionalMC02 that link didn’t work for me so I’m case you’re still wondering what’s going on basically long story short the creator isn’t keeping bot and so the bot only works if you already have it in your server it does not allow you to add it to servers as of two weeks ago but if you have it already in then it’s still working normal.
