### ISSUE TITLE
Error when running command

### ISSUE THREAD

**Issue by ghost** [EmoteBot/EmoteManager#21]
i went to selfhost this, and when i try use a command it doenst shows anything on console or channel
(btw this looks like prefix, but i don't see a way of config it on the config.py or something)

**Comment by saucylegs** [comment]
Yeah I got confused with that when I first set up the bot too. 

To set a prefix, add this somewhere in config.py:

```python
'prefixes': ['em/'],
```

Of course you can change the prefix to whatever you want, or add additional ones (like this `'prefixes': ['prefix1', 'prefix2'],`)

**Comment by ghost** [comment]
ty
