### ISSUE TITLE
wand.image failure

### ISSUE THREAD

**Issue by Shuridirty** [EmoteBot/EmoteManager#23]
when i tried to run the bot, it gave a warning "WARNING:utils.image:Failed to import wand.image. Image manipulation functions will be unavailable." which makes the bot unable to make emojis (i'm guessing because it needs to compress the emoji size) i have installed wand and everything else in the requirements so i don't why this isn't working, can i get help?

**Comment by ioistired** [comment]
You need to install ImageMagick https://imagemagick.org/script/download.php.
