### ISSUE TITLE
Emote Manager being private?

### ISSUE THREAD

**Issue by botpandabear11** [EmoteBot/EmoteManager#26]
![ADA61382-CCB2-4DB6-90CA-797DA0E5D7FC](https://user-images.githubusercontent.com/83625507/116956470-3283fc00-ac4a-11eb-843a-30136bb9ddc2.jpeg)

what is this about?

**Comment by kconradi87** [comment]
Yeah, it’s been that way for months now. If you already have the bot in your server then it still works. It was the bot owners personal decision. @botpandabear11
