### ISSUE TITLE
Cannot Add The Bot.

### ISSUE THREAD

**Issue by ghost** [EmoteBot/EmoteManager#30]
Hi, I cannot add the bot.

**Comment by ghost** [comment]
Upon Reading other issues, Can I host mw own, if o, how?

**Comment by ioistired** [comment]
Yes you can, please join the [support server](https://discord.gg/ZmTpXvaH) for assistance with that. Also due to an acquisition Emote Manager will be made public again soon.

**Comment by uhIgnacio-zz** [comment]
> Yes you can, please join the [support server](https://discord.gg/ZmTpXvaH) for assistance with that. Also due to an acquisition Emote Manager will be made public again soon.

inv is invalid now

**Comment by ioistired** [comment]
@uhIgnacio 9tTUaPSV
