### ISSUE TITLE
Better UX for rate limits

### ISSUE THREAD

**Issue by ioistired** [EmoteBot/EmoteManager#4]
Currently people see the bot typing for 30+ minutes and think it's broken. We should add a timeout of 15s or so. If it takes longer than that, cancel the typing context manager, say that the action may take a while and that the user will be pinged when it's done. When it is done, ping the user.

**Comment by ioistired** [comment]
Alternatively we can try and impl the option that raises on being rate limited. See https://discord.com/channels/336642139381301249/336642776609456130/727820830612127765

**Comment by StarrFox** [comment]
I think one way to fix this without messing with the discord.py internals is with an add/timer task setup 

add task: attempts to add the emotes and cancels the timer task on completion 

timer task: waits some amount of time and cancels the add task on completion

**Comment by ioistired** [comment]
Ideally we'd want to synchronize the adding operation with a per-guild Queue too. I'm thinking an `DefaultDict[discord.Guild, asyncio.Queue]` since the rate limits are guild-wide.

But for an initial implementation, just doing a timeout works too.

**Comment by ioistired** [comment]
Note to self: if I copy R. Danny, legally I must put his code in a separate file and import the functions I want.
